### ISSUE TITLE
Cannot set properties of undefined (setting 'width')

### ISSUE THREAD

**Issue by ekkelenkamp** [Deltares/fews-web-oc#150]
Testing with the latest pi request module, this is failing for me as well. Switching to another menu item, results in these errors:
This also happens without authentication enabled.

Compiled with problems:
×
ERROR
Cannot set properties of undefined (setting 'width')
TypeError: Cannot set properties of undefined (setting 'width')
at Map._resizeCanvas (webpack-internal:///./node_modules/mapbox-gl/dist/mapbox-gl.js:35:470267)
at Map.resize (webpack-internal:///./node_modules/mapbox-gl/dist/mapbox-gl.js:35:455247)
at VueComponent.resize (webpack-internal:///./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./node_modules/vue2mapbox-gl/src/components/VMapbox.vue?vue&type=script&lang=js&:177:18)

**Comment by ekkelenkamp** [comment]
See also: https://github.com/Deltares/fews-web-oc/pull/145
